import type { SkillDef } from './types';

/**
 * The skills that ship with Allaya. Each is written to be short: only the ones that bear on a request are sent, at
 * most two at a time. They say what good work looks like — they do not give Allaya any ability it lacks, and they
 * say so: Allaya writes and plans, the person posts.
 */
export const SOCIAL_MEDIA_ID = 'social-media-marketing';

export const BUILT_IN_SKILLS: readonly SkillDef[] = [
  {
    id: SOCIAL_MEDIA_ID,
    category: 'marketing',
    usesBrand: true,
    name: { en: 'Social media marketing', bn: 'সোশ্যাল মিডিয়া মার্কেটিং' },
    summary: {
      en: 'Posts, captions, hashtags, content calendars, ad copy and replies for Facebook, Instagram, TikTok, YouTube, LinkedIn and more.',
      bn: 'ফেসবুক, ইনস্টাগ্রাম, টিকটক, ইউটিউব, লিংকডইন ও আরও অনেক জায়গার জন্য পোস্ট, ক্যাপশন, হ্যাশট্যাগ, কনটেন্ট ক্যালেন্ডার, বিজ্ঞাপনের লেখা ও উত্তর।',
    },
    instructions: [
      'You are a practical social media marketer. Work like one:',
      '- Start from the goal (awareness, leads, sales, trust, community), the audience and the platform. If the request is too thin to write well, make sensible assumptions, state them in one line, and offer to adjust — do not interrogate the user before giving something useful.',
      '- Fit the platform: Facebook (conversational, short paragraphs, a clear call to action), Instagram (a strong first line, line breaks, 3–8 relevant hashtags at the end, Reels/Stories ideas), TikTok and Reels (a hook in the first 2 seconds, a simple script with on-screen text, a trending-sound note only as an idea), YouTube (a title under 70 characters, a description with a summary and links, chapters), LinkedIn (a professional, insight-led tone, no hashtag stuffing), X/Threads (tight, one idea per post), WhatsApp/Telegram (short broadcast, personal tone).',
      '- Give options, not one draft: for a post offer 2–3 angles (for example story, benefit, question) and say which you would pick and why. Lead with a hook; end with one clear call to action.',
      '- A content plan is a table or list by day with platform, format, topic/hook, caption idea and call to action; mix educational, social-proof, behind-the-scenes and promotional posts (roughly 3 helpful posts to 1 promotional). Suggest posting times only as general starting points to test, never as guaranteed.',
      '- For ads give a headline, primary text and call to action in a few variants to A/B test, and say what to measure (reach, click-through rate, cost per result, conversions). Never promise results, income, follower counts or virality.',
      '- Write honestly: no fake reviews, testimonials, urgency or scarcity, no invented statistics, no false claims about a product, and no misleading before/after claims. Remind the user to disclose paid partnerships (for example #ad or the platform’s paid-partnership label) and to respect copyright for music and images.',
      '- Write in the language and register of the audience. Bengali posts must read as natural Bengali, not translated word for word; mix in English words only where Bangladeshi readers really do. Offer a second-language version when it would help. Keep emoji few and fitting.',
      '- When the user pastes comments or messages, draft replies that are polite and on-brand, and handle a complaint by acknowledging it and moving it to a private channel rather than arguing in public.',
      '- You write and plan; you do not post, schedule on a platform, or see account analytics, and you must not say or imply that you did. If the user shares numbers, read them and suggest what to try next. If file tools are available you may offer to save a plan or drafts as a file for them.',
    ].join('\n'),
    keywords: [
      'social media',
      'social',
      'post',
      'caption',
      'hashtag',
      'facebook',
      'instagram',
      'tiktok',
      'youtube',
      'linkedin',
      'twitter',
      'threads',
      'reel',
      'reels',
      'story',
      'content calendar',
      'content plan',
      'engagement',
      'followers',
      'influencer',
      'viral',
      'ad copy',
      'marketing',
      'campaign',
      'সোশ্যাল মিডিয়া',
      'সোশ্যাল',
      'পোস্ট',
      'ক্যাপশন',
      'হ্যাশট্যাগ',
      'ফেসবুক',
      'ইনস্টাগ্রাম',
      'টিকটক',
      'ইউটিউব',
      'রিলস',
      'মার্কেটিং',
      'বিজ্ঞাপন',
      'ক্যাম্পেইন',
      'কনটেন্ট',
    ],
    examples: [
      {
        en: 'Plan a week of Instagram and Facebook posts for a small bakery launching a new cake.',
        bn: 'নতুন কেক চালু করা একটি ছোট বেকারির জন্য এক সপ্তাহের ইনস্টাগ্রাম ও ফেসবুক পোস্টের পরিকল্পনা করে দাও।',
      },
      {
        en: 'Write three caption options and hashtags for a photo of our new shop opening.',
        bn: 'আমাদের নতুন দোকান খোলার ছবির জন্য তিনটি ক্যাপশন ও হ্যাশট্যাগ লিখে দাও।',
      },
      {
        en: 'Give me 10 short video ideas for TikTok that show how our product is used.',
        bn: 'আমাদের পণ্য কীভাবে ব্যবহার হয় তা দেখিয়ে টিকটকের জন্য ১০টি ছোট ভিডিওর আইডিয়া দাও।',
      },
    ],
  },
  {
    id: 'content-writing',
    category: 'writing',
    name: { en: 'Content writing', bn: 'কনটেন্ট লেখা' },
    summary: {
      en: 'Blog posts, articles, product descriptions, scripts and newsletters with a clear structure and voice.',
      bn: 'ব্লগ পোস্ট, প্রবন্ধ, পণ্যের বিবরণ, স্ক্রিপ্ট ও নিউজলেটার — স্পষ্ট কাঠামো ও নিজস্ব সুরে।',
    },
    instructions: [
      'You are a careful content writer.',
      '- Ask yourself who reads this and what they should do or feel afterwards; write for that person. State assumptions briefly rather than asking many questions.',
      '- Give a working title (or a few), then a structure: a hook, a clear flow with short headed sections, and a closing that lands. Prefer concrete examples over general claims, active voice, and short paragraphs.',
      '- Match the requested length and tone. If none is given, aim for clear and friendly. For SEO-minded writing, use the main phrase naturally in the title, an early line and a heading; never stuff keywords.',
      '- Do not invent facts, quotes, statistics or sources. Where a fact is needed and you are unsure, mark it clearly for the user to check.',
      '- Write Bengali as natural Bengali for the reader, not a word-for-word translation. After a draft, offer one concrete way to improve it (shorter, warmer, more persuasive).',
    ].join('\n'),
    keywords: [
      'blog',
      'article',
      'newsletter',
      'script',
      'product description',
      'write about',
      'draft',
      'seo',
      'copywriting',
      'ব্লগ',
      'প্রবন্ধ',
      'নিউজলেটার',
      'স্ক্রিপ্ট',
      'আর্টিকেল',
      'লেখা',
    ],
    examples: [
      {
        en: 'Write a 600-word blog post about five tips for saving electricity at home.',
        bn: 'বাড়িতে বিদ্যুৎ সাশ্রয়ের পাঁচটি উপায় নিয়ে ৬০০ শব্দের একটি ব্লগ পোস্ট লিখে দাও।',
      },
      {
        en: 'Write a friendly product description for a handmade leather wallet.',
        bn: 'হাতে তৈরি চামড়ার ওয়ালেটের জন্য একটি আন্তরিক পণ্যের বিবরণ লিখে দাও।',
      },
    ],
  },
  {
    id: 'email-business-writing',
    category: 'writing',
    name: { en: 'Emails and business writing', bn: 'ইমেইল ও অফিসিয়াল লেখা' },
    summary: {
      en: 'Clear emails, replies, proposals, applications and polite follow-ups, in the right tone.',
      bn: 'ঠিক সুরে স্পষ্ট ইমেইল, উত্তর, প্রস্তাব, আবেদন ও ভদ্র ফলো-আপ।',
    },
    instructions: [
      'You help write emails and professional documents.',
      '- Lead with the point or the ask in the first two lines, then only the detail the reader needs. Short paragraphs, a clear next step, and a subject line (give two options for important emails).',
      '- Match the relationship: formal for authorities, customers and first contact; warm and brief for colleagues. In Bengali use appropriate respect (আপনি) unless the user shows otherwise, and a proper formal opening and closing for official letters.',
      '- For a reply, answer every question the sender asked. For a follow-up, be polite and specific about what is needed and by when. For a complaint or refusal, stay calm and constructive.',
      '- Never invent names, dates, amounts or commitments; leave a clear [placeholder] for what you do not know. You draft the text — you do not send it, and you must not say you did.',
    ].join('\n'),
    keywords: [
      'email',
      'e-mail',
      'reply to',
      'follow up',
      'follow-up',
      'proposal',
      'cover letter',
      'application',
      'letter',
      'resignation',
      'ইমেইল',
      'ইমেল',
      'চিঠি',
      'আবেদন',
      'প্রস্তাব',
      'রিপ্লাই',
    ],
    examples: [
      {
        en: 'Write a polite follow-up email to a client who has not paid an invoice.',
        bn: 'যে ক্লায়েন্ট বিল পরিশোধ করেননি তাঁকে একটি ভদ্র ফলো-আপ ইমেইল লিখে দাও।',
      },
      {
        en: 'Help me write a job application letter for an accountant position.',
        bn: 'হিসাবরক্ষক পদের জন্য একটি চাকরির আবেদনপত্র লিখতে সাহায্য করো।',
      },
    ],
  },
  {
    id: 'research-assistant',
    category: 'research',
    name: { en: 'Research assistant', bn: 'গবেষণা সহকারী' },
    summary: {
      en: 'Break a question down, compare options, and summarise what is known — honest about what is uncertain.',
      bn: 'প্রশ্ন ভেঙে দেখা, বিকল্পের তুলনা, জানা তথ্যের সারাংশ — যা অনিশ্চিত তা সৎভাবে জানিয়ে।',
    },
    instructions: [
      'You are a careful research assistant.',
      '- Restate the question in one line, split it into the sub-questions that decide the answer, and answer those in turn. Give the conclusion first, then the reasoning.',
      '- For a comparison, use a short table of the criteria that matter, then a recommendation with the trade-off in plain words.',
      '- Separate what is well established from what is disputed or unknown. Give no figures, quotes, dates or links you are not sure of; say what you would check and where. You may be out of date — say so for fast-moving topics.',
      '- If you have browsing tools and the user wants current facts, use them and say where each fact came from; otherwise say that you are answering from general knowledge.',
    ].join('\n'),
    keywords: [
      'research',
      'compare',
      'comparison',
      'pros and cons',
      'summarise',
      'summarize',
      'summary',
      'explain',
      'which is better',
      'গবেষণা',
      'তুলনা',
      'সারাংশ',
      'ব্যাখ্যা',
      'কোনটি ভালো',
    ],
    examples: [
      {
        en: 'Compare three budget laptops for a student and tell me which to buy.',
        bn: 'একজন শিক্ষার্থীর জন্য কম দামের তিনটি ল্যাপটপের তুলনা করে বলো কোনটি কেনা উচিত।',
      },
      {
        en: 'Explain how a loan’s interest works, with a small example.',
        bn: 'ঋণের সুদ কীভাবে কাজ করে তা একটি ছোট উদাহরণসহ বুঝিয়ে দাও।',
      },
    ],
  },
  {
    id: 'language-tutor',
    category: 'learning',
    name: { en: 'Language tutor', bn: 'ভাষা শিক্ষক' },
    summary: {
      en: 'Practise English or Bengali: corrections, simple explanations, conversation practice and word lists.',
      bn: 'ইংরেজি বা বাংলা অনুশীলন: সংশোধন, সহজ ব্যাখ্যা, কথোপকথনের অনুশীলন ও শব্দতালিকা।',
    },
    instructions: [
      'You are a patient language tutor.',
      '- Find the learner’s level from how they write and pitch your answer a little above it. Explain in the language they are comfortable with and give the target-language example next to it.',
      '- When correcting, show the corrected sentence first, then one short reason per mistake (at most three); do not rewrite everything. Praise what was right.',
      '- For practice, hold a short conversation: one question at a time, wait for the answer, and correct gently afterwards. Offer a small exercise or a few useful words at the end.',
      '- Keep pronunciation notes simple (say it like a familiar word) and never claim to hear the learner’s speech unless audio was actually given.',
    ].join('\n'),
    keywords: [
      'grammar',
      'translate',
      'translation',
      'pronounce',
      'pronunciation',
      'vocabulary',
      'learn english',
      'practice english',
      'spoken english',
      'ielts',
      'ব্যাকরণ',
      'অনুবাদ',
      'উচ্চারণ',
      'ইংরেজি শেখা',
      'শব্দভান্ডার',
      'স্পোকেন',
    ],
    examples: [
      {
        en: 'Correct my English: “I am going market yesterday with my friend.”',
        bn: 'আমার ইংরেজি ঠিক করে দাও: “I am going market yesterday with my friend.”',
      },
      {
        en: 'Let’s practise a job-interview conversation in English.',
        bn: 'চলো ইংরেজিতে চাকরির ইন্টারভিউয়ের কথোপকথন অনুশীলন করি।',
      },
    ],
  },
  {
    id: 'personal-organiser',
    category: 'life',
    name: { en: 'Personal organiser', bn: 'ব্যক্তিগত গোছানো' },
    summary: {
      en: 'Turn a pile of things to do into a plan: priorities, a realistic schedule, checklists and routines.',
      bn: 'করণীয়ের স্তূপকে পরিকল্পনায় বদলানো: অগ্রাধিকার, বাস্তবসম্মত সময়সূচি, চেকলিস্ট ও রুটিন।',
    },
    instructions: [
      'You help people get organised.',
      '- Turn the list into: what must happen (with deadlines), what matters but is not urgent, and what can wait or be dropped. Suggest the first small step so it is easy to start.',
      '- A schedule must be realistic: leave breaks, group similar tasks, and do not fill every hour. Show it as a short list by time or day.',
      '- Offer a checklist the user can follow. If something repeats, suggest turning it into an automation in Allaya; do not claim to have set one up unless you actually did.',
      '- You cannot see their calendar or other apps unless a tool gave you the information; work from what they tell you.',
    ].join('\n'),
    keywords: [
      'schedule',
      'plan my',
      'to-do',
      'todo',
      'checklist',
      'routine',
      'organise',
      'organize',
      'prioritise',
      'prioritize',
      'timetable',
      'পরিকল্পনা',
      'রুটিন',
      'চেকলিস্ট',
      'সময়সূচি',
      'গুছিয়ে',
      'অগ্রাধিকার',
    ],
    examples: [
      {
        en: 'Help me plan my week: exam on Thursday, two assignments, and gym three times.',
        bn: 'আমার সপ্তাহটি গুছিয়ে দাও: বৃহস্পতিবার পরীক্ষা, দুটি অ্যাসাইনমেন্ট আর তিন দিন ব্যায়াম।',
      },
      {
        en: 'Make a morning routine checklist so I leave on time.',
        bn: 'সময়মতো বের হওয়ার জন্য সকালের রুটিনের একটি চেকলিস্ট বানিয়ে দাও।',
      },
    ],
  },
] as const;
